### ISSUE TITLE
use react-native-pathjs-charts was wrong

### ISSUE THREAD

**Issue by smilexlong** [capitalone/react-native-pathjs-charts#1]
"react": "15.0.2",
 "react-native": "^0.26.3",
 "react-native-pathjs-charts": "0.0.19",

Warning:Native component for "RNSVGGroup" dose not exist
Warning:Native component for "RNSVGClipPath" dose not exist
Warning:Native component for "RNSVGPath" dose not exist
Warning:Native component for "RNSVGRect" dose not exist
Warning:Native component for "RNSVGCircle" dose not exist
Warning:Native component for "RNSVGEllipse" dose not exist
Warning:Native component for "RNSVGLine" dose not exist
Warning:Native component for "RNSVGSvgView" dose not exist
Warning:Native component for "RNSVGSvgText" dose not exist
Warning:Native component for "RNSVGSvgImage" dose not exist

**Comment by caledhwa** [comment]
Hmmm. I'll look into this in the next 24 hours. Might be an issue with the current versions. You did `npm link` or `react-native link`, right?

**Comment by smilexlong** [comment]
@caledhwa  yes, i did npm link

**Comment by caledhwa** [comment]
Cool. I'll check into it.

Get Outlook for iOS




On Mon, Aug 1, 2016 at 9:52 PM -0700, "smilexlong" <notifications@github.com> wrote:












@caledhwa  yes, i did npm link

**Comment by smilexlong** [comment]
@caledhwa  This error occurs in I use the android,If you found the problem, can you tell me,thank you

**Comment by caledhwa** [comment]
So, I had the same problem in that `rnpm link` and `react-native link` was not picking up the SVG library as it was a deeper dependency. 

Try this @smilexlong: 

```
rnpm link react-native-svg
```

That linked it for me. However, now I'm having a different issue with it getting to render on iOS and it is having a build failure on Android. I admit that I hadn't upgraded the library since I started my internal process with my company on open sourcing. However, I'm giving it a try to get to the latest version. I'll let you know how it goes. I've been using the internal library with 0.26 for awhile on our internal projects with no problem. But, now I'm up to 0.30 and noticing issues. Since the changes around linking that got merged into react-native itself, my instructions may need a fix. I'll see if I can figure it out.

Also @smilexlong - I'm on vacation so I may or may not get back quickly as I move between destinations. Sorry about that... Let me know if you have some success.

**Comment by caledhwa** [comment]
Also, looks like to support 0.30 react-native I'd need to update to use the new npm package (3.1.1 or 4.0.0 if it gets past RC). Gonna check that out as well. Since the library was working for me on 0.26, it should work for you if you can get the linking to actually work. Let me know.

**Comment by caledhwa** [comment]
After linking, I still had problems on Android with v0.30. Looks like not only do I need the new package (3.1.1) for **react-native-svg** but this issue might be in play (a closed issue on react-native-svg: https://github.com/magicismight/react-native-svg/issues/83 - Putting this here for reference. Also, something you could try. Sorry for the issues, gonna get it figured out.

By the way, you should get output from linking that looks something like this:

```
react-native link react-native-svg

rnpm-link info Linking react-native-svg android dependency 
rnpm-link info Android module react-native-svg has been successfully linked 
rnpm-link info Linking react-native-svg ios dependency 
rnpm-link info iOS module react-native-svg has been successfully linked 
```

Based on my experience with linking now that it's in react-native is this: it is not finding dependent packages. I am going to ping Mike Grabowski on this to find out why it stopped working.

**Comment by caledhwa** [comment]
So, I can't verify that it will work with your versions for sure. However, I was able to make sure it all worked with an update to the latest `react-native-svg` library as long as linking is done correctly. Please give it a try now. Do an npm update of the library (it's now 0.0.20).

This PR #3 fixed the reference to the latest react-native-svg library. 

Give it a try and let me know how it goes.

**Comment by smilexlong** [comment]
ok,i will try again  what like you say. And then tell you the result

**Comment by caledhwa** [comment]
Any luck @smilexlong?

**Comment by smilexlong** [comment]
@caledhwa yes,I try it on the latest version and it work,thank you for your help

**Comment by caledhwa** [comment]
Woo hoo! Thanks!
