### ISSUE TITLE
"fetch" is undefined after importing react-native-pathjs-charts

### ISSUE THREAD

**Issue by adriansoghoian** [capitalone/react-native-pathjs-charts#129]
Before filing an issue please ensure the following boxes are checked, if applicable:

- [ Yes ] I have searched for existing issues
- [ Yes ] I have provided detailed instructions that can reproduce the issue (including code and data necessary)

--------------
(Apologies if this is a newb issue) 

This library looks wonderful - thank you for making it available! After installing and linking the library, my app will build fine...but when I import a component from the library, I start seeing strange errors, such as RN not being able to recognize the built-in "fetch" function. Do you have any idea what could cause this? 

I imagine it may be related to my package.json, which I've pasted snippets of below. Thank you so much for the help!!

```
"dependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "react": "15.3.2",
    "react-native": "0.42.0",
    "react-native-pathjs-charts": "0.0.26",
    "react-native-svg": "^5.1.6"
},
"devDependencies": {
    "babel-jest": "17.0.0",
    "babel-plugin-transform-decorators": "^6.22.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native": "1.9.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest": "17.0.1",
    "jest-react-native": "17.0.1",
    "react-test-renderer": "15.3.2"
  }
```

**Comment by marzolfb** [comment]
I have yet to use this library after upgrading to react-native 0.42 and I'm not sure what side effects are possible - what you describe above might be related to that. Try downgrading to 0.41 and see if you still have an issue?

Also, there will be conflicts with this library using a newer version of react-native-svg. You will want to downgrade that version to 4.5 for the best results (there are number of issues you can look through on this project explaining why we are sticking with react-native-svg 4.5).

**Comment by adriansoghoian** [comment]
Thanks @marzolfb! What version of react would you recommend using as well?

**Comment by franverona** [comment]
Same problem here :(

**Comment by marzolfb** [comment]
i know its been awhile on this one - @adriansoghoian, did you wind up doing something similar to @franverona ?

**Comment by Amnok** [comment]
getting the same issue When using  NetInfo.fetch().done((reach)

**Comment by aramboyajyan** [comment]
I had the same issue and it was resolved by removing the `.done()`, like @franverona mentioned.

Thanks!

**Comment by marzolfb** [comment]
I'm actually curious why others started with an assumption that `done()` was required when invoking `fetch()`. The[ fetch API that react-native uses](https://facebook.github.io/react-native/docs/network.html#using-fetch) returns a es6 built-in promise and that doesn't have a `done` method - see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) ([this SO question/answer](http://stackoverflow.com/questions/26667598/will-javascript-es6-promise-support-done-api) also provides some interesting background).

My only guess is that some of the confusion comes from thinking that the fetch API is similar to [jQuery's Deferred object](https://api.jquery.com/category/deferred-object/) or perhaps some other older promises library that implements done.

In any event, this is really a question specific to react-native and its use of the fetch API rather than this particular charting library. Closing it now but I appreciate all the info from everyone.
