### ISSUE TITLE
In Bars chart first line hide yAxis numbers

### ISSUE THREAD

**Issue by SimchaShats** [capitalone/react-native-pathjs-charts#25]
First bar hide yAxis numbers...
![screenshot_2016-11-15-15-04-47](https://cloud.githubusercontent.com/assets/19427778/20306829/30178910-ab45-11e6-85a4-b14225bc4dd6.png)

**Comment by SimchaShats** [comment]
The same thing I think on P
![screenshot_2016-11-15-16-00-24](https://cloud.githubusercontent.com/assets/19427778/20308645/96238c6a-ab4d-11e6-9386-be045f909e6c.png)
ie chart

**Comment by kasperwandahl** [comment]
I don't know if it helps, but in the file Bar.js at line 134 you have <Axis ... />, move this line down until it's below the <G>{lines} </G> tag. Then you'll see the numbers on top, but the lines will also go on top of the bars.

**Comment by marzolfb** [comment]
Looks like #27 addresses your first issue with the y-axis labels being covered by the bars. Once we get that merged to master, it would be great if you could verify that fixes it for your example. 

The pie chart example is different. I do see an extra G element (dealing with offset handling) that looks like its impacting the text labels being "centered" within each pie section. However, the problem with the example is that the combination of the length of the labels, the font size/weight, and the size of the chart make it so that the text is too big to fit into each pie section. There's also no concept of "wrapping" a label and constraining it to a particular width to fit within the pie section (is that basically what you are asking for?). I would suggest adjusting your labels to be smaller in length (if possible) and/or changing the font size/weight settings. If you see a way we can enhance the library in a generic manner to address this issue, please open a new issue and offer a proposal.

I will close this for addressing the bar chart example once we get #27 merged in and as noted above, you're welcome to add a new issue to address the pie chart problem.

**Comment by marzolfb** [comment]
#27 was merged in so closing this one now.
