### ISSUE TITLE
Missing onload property

### ISSUE THREAD

**Issue by jasmo2** [capitalone/react-native-pathjs-charts#59]
Is not an issue but it will be awesome to have a onload property while the chart is loading

**Comment by marzolfb** [comment]
Since this library itself doesn't implement any native modules itself to perform svg rendering and instead defers to react-native-svg for that functionality, I don't think adding an onload property to this library is possible without it first being available in react-native-svg. Checking over there, I did see this issue that has been open since November 2016: https://github.com/react-native-community/react-native-svg/issues/183

Given all of that, I think I'd like to close this issue here and possibly reopen or add a new issue for this if and when react-native-svg has this capability in the future. Do you have any objections or have any other ideas that could workaround the dependence on react-native-svg for this enhancement?
