### ISSUE TITLE
Update react-native-svg to fix error

### ISSUE THREAD

**Issue by tiaaaa123** [capitalone/react-native-pathjs-charts#74]
You should update `react-native-svg` to 4.5.0 or higher. They added support for `react-native@0.40.0`, which would be great because I can't use your module on iOS.

Having this issue: 
<img width="399" alt="redscreen" src="https://cloud.githubusercontent.com/assets/9055082/22699761/713c7ab8-ed26-11e6-8002-0d64a97381e1.png">

Tried to build in xCode and got all those errors :
![xvode](https://cloud.githubusercontent.com/assets/9055082/22699764/731ed77c-ed26-11e6-99d8-0e6b6b38ce89.png)

**Comment by tiaaaa123** [comment]
By installing directly `react-native-svg` in the project (and linking it), there are no more error, but at the very moment the app render the Chart, the app crash and close. Any Idea?

**Comment by marzolfb** [comment]
Agreed - I want to upgrade to react-native 0.40 and react-native-svg 4.5.0 too. #69 addresses that and I just sent a followup comment to see where we are with that. If necessary I will push a separate PR through that updates the dependencies very soon to address this since several folks are hitting this wall.

Regarding the crashing behavior on iOS, this is actually the same thing happening in #70 - if you tried running your setup in an Android emulator, you'd get a "Error while updating property 'd' in shadow node of type RNSVGPath" error. The only way I see around either of these behaviors is updating the react-native and react-native-svg versions.

**Comment by marzolfb** [comment]
Just published version 0.0.25 which upgrades dependencies for react-native to 0.41.2 and react-native-svg to 4.5.0

**Comment by afilp** [comment]
@marzolfb Does this work with react native 0.42? Because I still get this 'd' error in Android.

**Comment by marzolfb** [comment]
@aflip I haven't tried with rn .42 yet - could you open a new issue for us to track this separately?
