### ISSUE TITLE
SmoothLine graph plot doesn't actually go through data points

### ISSUE THREAD

**Issue by Cody-G-G** [capitalone/react-native-pathjs-charts#83]
I'm not exactly sure if this is expected behavior or not, but here's an example:

        let data = [[
            {"x": 8, "y": 82},
            {"x": 13, "y": 70},
            {"x": 15, "y": 120},
            {"x": 19, "y": 80}
        ]]

        let regions = [{
            label: '',
            from: 70,
            to: 130,
            fill: '#18c947'
        }]

![16729614_1253781768025289_1799773077_n](https://cloud.githubusercontent.com/assets/9220445/22857834/63a28e56-f0a5-11e6-8a8e-0c037ea98054.png)

As you can see, even though the datapoint is right on the edge of the region, the plot goes under it, which is deceiving and gives the impression that the value is outside of the bounds designated by the region.

**Comment by marzolfb** [comment]
Interesting. Looks like a bug but I am very curious why your graph starts at (30,8) instead of (0,0), whether that was intentional (I'm guessing not), and if so, how you did it?

Just for a reference point, could you provide some dependency versions you are working with - what is the output of this for you:

```
npm list react-native react-native-svg paths-js
```

**Comment by Cody-G-G** [comment]
It is intentional, my X axis represents hours of the day (24-hour system), and my first data point starts at X = 8. I have also set min = 30, since Y represents blood blucose levels in mg/dl. Therefore, the graph would start at (min, first X value in dataset), which is (30, 8) in my example. The output of that command is:

```
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.4.0
npm info ok
npm info it worked if it ends with ok
npm info using npm@4.1.1
npm info using node@v6.4.0
glucowise@0.0.1 C:\Work\Projects\ReactNative\GlucoWise
+-- react-native@0.41.0
-- react-native-pathjs-charts@0.0.25
  +-- paths-js@0.4.5
  -- react-native-svg@4.5.0

npm info ok

```

**Comment by marzolfb** [comment]
All the version info looks fine. On looking at your data and image a second time, it visually looks to me like your one data point `{"x": 13, "y": 70}` is indeed in your green region band set with a min y of 70. Given this is a SmoothLine and not a StockLine graph, I guess I would expect that curve drawn between the first two data points could/should dip below your region band (in order to get back up to your 3rd data point). Does that make sense? Would you expect different behavior? Is StockLine a better choice for what you are trying to achieve?

**Comment by Cody-G-G** [comment]
Yes, StockLine is a better choice, and it's what I'm really using, but this came up during my testing and I still wanted to bring it up since it looks to me that the curve is being drawn too steep, which is indeed why the curve goes under the region. I mean, even though it's a SmoothLine, I would still expect the plot to actually represent the range of values that can be found in my dataset. I'm not sure if that makes sense but to me this example illustrates how a SmoothLine would be deceiving in certain scenarios, and even though with the lines being smooth those curves will not represent my actual data, the range should still be represented, which would be achieved by drawing the curves less steep.

It's probably not that big of a deal and would only be accentuated in certain scenarios I guess, it's also probably a dependency issue (I'm not sure), but just felt like opening an issue because it's behavior I wouldn't have expected. If you believe this is expected behavior and/or isn't really an issue that can or should be addressed, feel free to close it.

**Comment by marzolfb** [comment]
Thanks for the great feedback. 

Largely paths-js is providing the path/curve of the line here, so even if I agreed this were an issue, I'd likely have to submit an issue/PR to that project in order to "fix" this (I'm agreeing with your "probably a dependency issue" comment). 

The aspect of this scenario that makes the steepness of the curve seem reasonable to me is the small number of data points available for a path to be drawn - I think with more data points in play, the problem becomes less pronounced/non-existent. Ultimately though, I think we are in agreement that the StockLine is a better choice given what you are trying to convey.

What would probably help for the consumer of a chart like this would be to have circles/markers visible at each data point to make it clear where data points fell in the region. I think this is adequately captured in #40 which is still open.

With all that I said above, I'm inclined to close this out now but always willing to reconsider if new information presents itself.
