### ISSUE TITLE
High performance impact when dataset only contains small floats

### ISSUE THREAD

**Issue by Cody-G-G** [capitalone/react-native-pathjs-charts#94]
It takes upwards of 20-25 seconds to re-render the graph when the dataset only contains values such as: `[[{x: 0.01, y: 50}, {x: 0.02, y:70}, {x: 0.03, y:90}]]`

Also, the higher the precision of the floats, the higher performance impact there is, so if I have  `[[{x: 0.00001, y: 50},{x: 0.00009, y:70}]]`, the app will just freeze indefinitely.

**Comment by marzolfb** [comment]
Bummer. I'm assuming performance here is ugly regardless of platform but I just want to ask about the environment you are seeing problems under. Are you witnessing performance problems on Android or iOS or both? Emulator or actual device?

**Comment by Cody-G-G** [comment]
Android, Nexus 5, actual device.

**Comment by marzolfb** [comment]
While I'm still looking into this one (finding the right performance evaluation tooling to help has been challenging), I am curious if you try either of the two techniques if you see any noticeable improvement?

- Use static `tickValues` instead of letting the library figure out the tick values for you - something like this in the options for your chart:
```
...
tickValues: [
          {value:0.01},
          {value:0.02},
          {value:0.03},
        ],
...
```

- Use version 0.0.25 of this library - I'm wondering if #91 is problematic from a performance standpoint

Also, if I take your x values out one more decimal place to the right, I don't even see them displayed on the x axis (which is obviously a bug), do you see the same behavior?
